### ISSUE TITLE
iBlazr 1

### ISSUE THREAD

**Issue by tanken** [ConcepterDev/iblazr-sdk-android#1]
Hi there, 

I dont see any examples for version 1 iblazr. May i know if this sdk works for that, triggering with the audio signals? 

Thankss

**Comment by Worien** [comment]
Hello, 
Unfortunately we have not yet posted sdk for iblazr original, but we are going to do it soon.

**Comment by Worien** [comment]
Hi, we added the ability to interact with iblazr Original. Please look at the sample and documentation and if you want some new features you can create issues here.

**Comment by tanken** [comment]
Hey Team iBlazr,

Thanks a lot for the update.
Will explore with the new apis.
For a start, can I wake the iblazr without pressing the button (ie 800Hz, 200±150ms as per protocol).
If so, how do i call them?

Best,
Ken

**Comment by andrew-skrypnyk** [comment]
Hello Tanken.
It's sad news, but isn't possible, the only way to turn on iblazr - is Push power button.
